# This workflow is named "Generate Pipeline & Repo Info Excel"
name: Generate Pipeline & Repo Info Excel - Color

# This workflow can be triggered manually from the GitHub Actions UI.
# It now includes an 'environment' input parameter.
on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the target environment' # Description for the input
        required: true                             # This input is mandatory
        type: choice                               # The input will be a dropdown choice
        options:                                   # Available options for the environment
          - 'development'
          - 'staging'
          - 'production'
        default: 'development'                     # Default selected option

# Define the jobs (stages) for this workflow
jobs:
  # Stage 1: Create the Excel file
  create_excel:
    runs-on: windows-latest # This job will run on a Windows-based runner.
    outputs:
      # Define outputs from this job if needed by subsequent jobs.
      excel_file_path: pipeline_repo_info.xlsx # Output the path to the created Excel file

    steps:
      # Step 1: Checkout the repository code.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Cache PowerShell modules.
      - name: Cache PowerShell Modules
        uses: actions/cache@v4
        with:
          path: |
            C:\Users\runneradmin\Documents\PowerShell\Modules # Default path for CurrentUser scope
            C:\Program Files\PowerShell\Modules # Common path for AllUsers scope
          key: ${{ runner.os }}-powershell-modules-v1 # Unique key for the cache
          restore-keys: |
            ${{ runner.os }}-powershell-modules- # Fallback key for partial match

      # Step 3: Execute the PowerShell script to create the Excel file.
      # We are now passing the workflow name, run number, repository name, full commit SHA, AND the environment.
      - name: Execute PowerShell Script and Create Excel
        shell: powershell # Specify PowerShell as the shell for this step
        run: |
          # The script path is relative to the root of your repository.
          # -PipelineName: The name of the currently running workflow.
          # -RunNumber: The unique incremental number for each workflow run in a repository.
          # -RepoName: The name of the GitHub repository (e.g., 'my-org/my-repo').
          # -CommitSha: The full SHA of the commit that triggered the workflow.
          # -Environment: The environment chosen by the user via workflow_dispatch.
          ./scripts/create-excel-report-pipeline-color.ps1 `
            -PipelineName "${{ github.workflow }}" `
            -RunNumber "${{ github.run_number }}" `
            -RepoName "${{ github.repository }}" `
            -CommitSha "${{ github.sha }}" `
            -Environment "${{ github.event.inputs.environment }}" # <--- Added environment input

      # Step 4: Upload the generated Excel file as an artifact from this job.
      - name: Upload Excel File for Publishing
        uses: actions/upload-artifact@v4
        with:
          name: excel-report-for-publish
          path: pipeline_repo_info.xlsx
          retention-days: 1

  # Stage 2: Publish the Excel file
  publish_excel:
    runs-on: ubuntu-latest
    needs: create_excel

    steps:
      # Step 1: Download the Excel file artifact created by the 'create_excel' job.
      - name: Download Excel File Artifact
        uses: actions/download-artifact@v4
        with:
          name: excel-report-for-publish
          path: .

      # Step 2: Publish the Excel file as a final workflow artifact.
      - name: Publish Excel File
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-repo-info-excel
          path: pipeline_repo_info.xlsx
          retention-days: 5
